name: snowflake
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - fastapi==0.115.0
      - uvicorn==0.30.0
      - torch==2.3.0
      - torchvision==0.18.0
      - torchaudio==2.3.0
      - opencv-python==4.10.0
      - pillow
      - numpy
      - pydantic
      - python-multipart
      - segment-anything
